horizonte = 10
rodales = 36

[random]
seed = 4 # random number generator seed
# min, max
edades = [1, 18]
has = [5, 15]

# min, max, step
[pino]
podas = [5, 15, 5]
raleos = [6, 11,1]
cosechas = [18, 29, 1]

[eucalyptus]
podas = [4, 6, 2]
cosechas = [8, 13,1]

