horizonte = 10
rodales = 15

[random]
seed = 17 # random number generator seed
# min, max
edades = [0, 30]
has = [5, 15]
# min, max, step
podas = [5, 15, 5]
raleos = [6, 30, 4]
cosechas = [13, 30, 4]

